import * as mongoose from 'mongoose';

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/privon';

const CitySchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    country: { type: String, required: true },
    state: String,
    isCapital: { type: Boolean, default: false },
    isDestination: { type: Boolean, default: false },
    countryCode: String,
  },
  { timestamps: true },
);

CitySchema.index({ name: 1, country: 1 }, { unique: true });

const CityModel = mongoose.model('City', CitySchema);

const CAPITALS = new Set([
  'Washington D.C.', 'Ottawa', 'London', 'Dublin', 'Paris', 'Berlin',
  'Rome', 'Madrid', 'Amsterdam', 'Brussels', 'Bern', 'Vienna',
  'Prague', 'Budapest', 'Warsaw', 'Stockholm', 'Oslo', 'Copenhagen',
  'Helsinki', 'Reykjavik', 'Lisbon', 'Athens', 'Bucharest', 'Sofia',
  'Zagreb', 'Ljubljana', 'Belgrade', 'Tallinn', 'Riga', 'Vilnius',
  'Valletta', 'Nicosia', 'Bratislava', 'Ankara', 'Abu Dhabi', 'Riyadh',
  'Doha', 'Kuwait City', 'Manama', 'Muscat', 'Beirut', 'Jerusalem',
  'Amman', 'Cairo', 'Tokyo', 'Seoul', 'Beijing', 'Taipei',
  'Singapore', 'Bangkok', 'Kuala Lumpur', 'Jakarta', 'Manila', 'Hanoi',
  'Phnom Penh', 'Delhi', 'Kathmandu', 'Colombo', 'Nairobi', 'Tunis',
  'Algiers', 'Accra', 'Addis Ababa', 'Kigali', 'Wellington',
  'Buenos Aires', 'Brasília', 'Mexico City', 'Bogotá', 'Lima',
  'Santiago', 'Montevideo', 'Panama City', 'San José', 'Quito',
  'Havana', 'Kingston', 'Nassau', 'Moscow', 'Kyiv', 'Baku',
  'Tbilisi', 'Yerevan', 'Tashkent',
]);

const COUNTRY_CODES: Record<string, string> = {
  'United States': 'US', 'Canada': 'CA', 'United Kingdom': 'GB',
  'Ireland': 'IE', 'France': 'FR', 'Germany': 'DE', 'Italy': 'IT',
  'Spain': 'ES', 'Netherlands': 'NL', 'Belgium': 'BE', 'Switzerland': 'CH',
  'Austria': 'AT', 'Czech Republic': 'CZ', 'Hungary': 'HU', 'Poland': 'PL',
  'Sweden': 'SE', 'Norway': 'NO', 'Denmark': 'DK', 'Finland': 'FI',
  'Iceland': 'IS', 'Portugal': 'PT', 'Greece': 'GR', 'Monaco': 'MC',
  'Luxembourg': 'LU', 'Romania': 'RO', 'Bulgaria': 'BG', 'Croatia': 'HR',
  'Slovenia': 'SI', 'Serbia': 'RS', 'Estonia': 'EE', 'Latvia': 'LV',
  'Lithuania': 'LT', 'Malta': 'MT', 'Cyprus': 'CY', 'Slovakia': 'SK',
  'Turkey': 'TR', 'India': 'IN', 'Nepal': 'NP', 'Sri Lanka': 'LK',
  'Pakistan': 'PK', 'South Africa': 'ZA', 'Kenya': 'KE', 'Morocco': 'MA',
  'Tunisia': 'TN', 'Algeria': 'DZ', 'Nigeria': 'NG', 'Ghana': 'GH',
  'Ethiopia': 'ET', 'Tanzania': 'TZ', 'Rwanda': 'RW', 'Australia': 'AU',
  'New Zealand': 'NZ', 'Argentina': 'AR', 'Brazil': 'BR', 'Mexico': 'MX',
  'Colombia': 'CO', 'Peru': 'PE', 'Chile': 'CL', 'Uruguay': 'UY',
  'Panama': 'PA', 'Costa Rica': 'CR', 'Ecuador': 'EC', 'Cuba': 'CU',
  'Jamaica': 'JM', 'Bahamas': 'BS', 'Russia': 'RU', 'Ukraine': 'UA',
  'Azerbaijan': 'AZ', 'Georgia': 'GE', 'Armenia': 'AM', 'Kazakhstan': 'KZ',
  'Uzbekistan': 'UZ', 'Japan': 'JP', 'South Korea': 'KR', 'China': 'CN',
  'Taiwan': 'TW', 'Singapore': 'SG', 'Thailand': 'TH', 'Malaysia': 'MY',
  'Indonesia': 'ID', 'Philippines': 'PH', 'Vietnam': 'VN', 'Cambodia': 'KH',
  'United Arab Emirates': 'AE', 'Saudi Arabia': 'SA', 'Qatar': 'QA',
  'Kuwait': 'KW', 'Bahrain': 'BH', 'Oman': 'OM', 'Lebanon': 'LB',
  'Israel': 'IL', 'Jordan': 'JO', 'Egypt': 'EG', 'Puerto Rico': 'PR',
};

const WORLDWIDE_CITIES = [
  { name: "New York", country: "United States", state: "New York" },
  { name: "Los Angeles", country: "United States", state: "California" },
  { name: "Chicago", country: "United States", state: "Illinois" },
  { name: "Houston", country: "United States", state: "Texas" },
  { name: "Miami", country: "United States", state: "Florida" },
  { name: "San Francisco", country: "United States", state: "California" },
  { name: "Las Vegas", country: "United States", state: "Nevada" },
  { name: "Washington D.C.", country: "United States" },
  { name: "Boston", country: "United States", state: "Massachusetts" },
  { name: "Seattle", country: "United States", state: "Washington" },
  { name: "Atlanta", country: "United States", state: "Georgia" },
  { name: "Dallas", country: "United States", state: "Texas" },
  { name: "Austin", country: "United States", state: "Texas" },
  { name: "Denver", country: "United States", state: "Colorado" },
  { name: "Nashville", country: "United States", state: "Tennessee" },
  { name: "New Orleans", country: "United States", state: "Louisiana" },
  { name: "Portland", country: "United States", state: "Oregon" },
  { name: "San Diego", country: "United States", state: "California" },
  { name: "Phoenix", country: "United States", state: "Arizona" },
  { name: "Minneapolis", country: "United States", state: "Minnesota" },
  { name: "Detroit", country: "United States", state: "Michigan" },
  { name: "Philadelphia", country: "United States", state: "Pennsylvania" },
  { name: "Charlotte", country: "United States", state: "North Carolina" },
  { name: "San Antonio", country: "United States", state: "Texas" },
  { name: "San Jose", country: "United States", state: "California" },
  { name: "Columbus", country: "United States", state: "Ohio" },
  { name: "Indianapolis", country: "United States", state: "Indiana" },
  { name: "Toronto", country: "Canada", state: "Ontario" },
  { name: "Vancouver", country: "Canada", state: "British Columbia" },
  { name: "Montreal", country: "Canada", state: "Quebec" },
  { name: "Calgary", country: "Canada", state: "Alberta" },
  { name: "Ottawa", country: "Canada", state: "Ontario" },
  { name: "Edmonton", country: "Canada", state: "Alberta" },
  { name: "Quebec City", country: "Canada", state: "Quebec" },
  { name: "London", country: "United Kingdom" },
  { name: "Manchester", country: "United Kingdom" },
  { name: "Edinburgh", country: "United Kingdom" },
  { name: "Glasgow", country: "United Kingdom" },
  { name: "Birmingham", country: "United Kingdom" },
  { name: "Liverpool", country: "United Kingdom" },
  { name: "Bristol", country: "United Kingdom" },
  { name: "Leeds", country: "United Kingdom" },
  { name: "Oxford", country: "United Kingdom" },
  { name: "Cambridge", country: "United Kingdom" },
  { name: "Bath", country: "United Kingdom" },
  { name: "Dublin", country: "Ireland" },
  { name: "Cork", country: "Ireland" },
  { name: "Paris", country: "France" },
  { name: "Lyon", country: "France" },
  { name: "Nice", country: "France" },
  { name: "Bordeaux", country: "France" },
  { name: "Marseille", country: "France" },
  { name: "Strasbourg", country: "France" },
  { name: "Toulouse", country: "France" },
  { name: "Berlin", country: "Germany" },
  { name: "Munich", country: "Germany" },
  { name: "Frankfurt", country: "Germany" },
  { name: "Hamburg", country: "Germany" },
  { name: "Düsseldorf", country: "Germany" },
  { name: "Cologne", country: "Germany" },
  { name: "Stuttgart", country: "Germany" },
  { name: "Heidelberg", country: "Germany" },
  { name: "Rome", country: "Italy" },
  { name: "Milan", country: "Italy" },
  { name: "Florence", country: "Italy" },
  { name: "Venice", country: "Italy" },
  { name: "Naples", country: "Italy" },
  { name: "Turin", country: "Italy" },
  { name: "Bologna", country: "Italy" },
  { name: "Madrid", country: "Spain" },
  { name: "Barcelona", country: "Spain" },
  { name: "Seville", country: "Spain" },
  { name: "Valencia", country: "Spain" },
  { name: "Bilbao", country: "Spain" },
  { name: "Málaga", country: "Spain" },
  { name: "Marbella", country: "Spain" },
  { name: "San Sebastián", country: "Spain" },
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Rotterdam", country: "Netherlands" },
  { name: "The Hague", country: "Netherlands" },
  { name: "Brussels", country: "Belgium" },
  { name: "Antwerp", country: "Belgium" },
  { name: "Bruges", country: "Belgium" },
  { name: "Zurich", country: "Switzerland" },
  { name: "Geneva", country: "Switzerland" },
  { name: "Basel", country: "Switzerland" },
  { name: "Bern", country: "Switzerland" },
  { name: "Lausanne", country: "Switzerland" },
  { name: "Lugano", country: "Switzerland" },
  { name: "Vienna", country: "Austria" },
  { name: "Salzburg", country: "Austria" },
  { name: "Innsbruck", country: "Austria" },
  { name: "Graz", country: "Austria" },
  { name: "Prague", country: "Czech Republic" },
  { name: "Brno", country: "Czech Republic" },
  { name: "Budapest", country: "Hungary" },
  { name: "Warsaw", country: "Poland" },
  { name: "Krakow", country: "Poland" },
  { name: "Wroclaw", country: "Poland" },
  { name: "Gdansk", country: "Poland" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Gothenburg", country: "Sweden" },
  { name: "Oslo", country: "Norway" },
  { name: "Bergen", country: "Norway" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Aarhus", country: "Denmark" },
  { name: "Helsinki", country: "Finland" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Porto", country: "Portugal" },
  { name: "Athens", country: "Greece" },
  { name: "Thessaloniki", country: "Greece" },
  { name: "Monaco", country: "Monaco" },
  { name: "Luxembourg City", country: "Luxembourg" },
  { name: "Bucharest", country: "Romania" },
  { name: "Sofia", country: "Bulgaria" },
  { name: "Zagreb", country: "Croatia" },
  { name: "Ljubljana", country: "Slovenia" },
  { name: "Belgrade", country: "Serbia" },
  { name: "Tallinn", country: "Estonia" },
  { name: "Riga", country: "Latvia" },
  { name: "Vilnius", country: "Lithuania" },
  { name: "Valletta", country: "Malta" },
  { name: "Nicosia", country: "Cyprus" },
  { name: "Limassol", country: "Cyprus" },
  { name: "Bratislava", country: "Slovakia" },
  { name: "Istanbul", country: "Turkey" },
  { name: "Ankara", country: "Turkey" },
  { name: "Izmir", country: "Turkey" },
  { name: "Antalya", country: "Turkey" },
  { name: "Dubai", country: "United Arab Emirates" },
  { name: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "Riyadh", country: "Saudi Arabia" },
  { name: "Jeddah", country: "Saudi Arabia" },
  { name: "Doha", country: "Qatar" },
  { name: "Kuwait City", country: "Kuwait" },
  { name: "Manama", country: "Bahrain" },
  { name: "Muscat", country: "Oman" },
  { name: "Beirut", country: "Lebanon" },
  { name: "Tel Aviv", country: "Israel" },
  { name: "Jerusalem", country: "Israel" },
  { name: "Amman", country: "Jordan" },
  { name: "Cairo", country: "Egypt" },
  { name: "Alexandria", country: "Egypt" },
  { name: "Tokyo", country: "Japan" },
  { name: "Osaka", country: "Japan" },
  { name: "Kyoto", country: "Japan" },
  { name: "Yokohama", country: "Japan" },
  { name: "Seoul", country: "South Korea" },
  { name: "Busan", country: "South Korea" },
  { name: "Beijing", country: "China" },
  { name: "Shanghai", country: "China" },
  { name: "Hong Kong", country: "China" },
  { name: "Guangzhou", country: "China" },
  { name: "Shenzhen", country: "China" },
  { name: "Chengdu", country: "China" },
  { name: "Taipei", country: "Taiwan" },
  { name: "Singapore", country: "Singapore" },
  { name: "Bangkok", country: "Thailand" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Jakarta", country: "Indonesia" },
  { name: "Manila", country: "Philippines" },
  { name: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Phnom Penh", country: "Cambodia" },
  { name: "Mumbai", country: "India", state: "Maharashtra" },
  { name: "Delhi", country: "India" },
  { name: "Bangalore", country: "India", state: "Karnataka" },
  { name: "Hyderabad", country: "India", state: "Telangana" },
  { name: "Chennai", country: "India", state: "Tamil Nadu" },
  { name: "Kolkata", country: "India", state: "West Bengal" },
  { name: "Kathmandu", country: "Nepal" },
  { name: "Colombo", country: "Sri Lanka" },
  { name: "Karachi", country: "Pakistan" },
  { name: "Lahore", country: "Pakistan" },
  { name: "Cape Town", country: "South Africa" },
  { name: "Johannesburg", country: "South Africa" },
  { name: "Durban", country: "South Africa" },
  { name: "Nairobi", country: "Kenya" },
  { name: "Marrakech", country: "Morocco" },
  { name: "Casablanca", country: "Morocco" },
  { name: "Fez", country: "Morocco" },
  { name: "Tunis", country: "Tunisia" },
  { name: "Algiers", country: "Algeria" },
  { name: "Lagos", country: "Nigeria" },
  { name: "Accra", country: "Ghana" },
  { name: "Addis Ababa", country: "Ethiopia" },
  { name: "Dar es Salaam", country: "Tanzania" },
  { name: "Kigali", country: "Rwanda" },
  { name: "Sydney", country: "Australia", state: "New South Wales" },
  { name: "Melbourne", country: "Australia", state: "Victoria" },
  { name: "Brisbane", country: "Australia", state: "Queensland" },
  { name: "Perth", country: "Australia", state: "Western Australia" },
  { name: "Adelaide", country: "Australia", state: "South Australia" },
  { name: "Auckland", country: "New Zealand" },
  { name: "Wellington", country: "New Zealand" },
  { name: "Buenos Aires", country: "Argentina" },
  { name: "São Paulo", country: "Brazil" },
  { name: "Rio de Janeiro", country: "Brazil" },
  { name: "Brasília", country: "Brazil" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Guadalajara", country: "Mexico" },
  { name: "Monterrey", country: "Mexico" },
  { name: "Bogotá", country: "Colombia" },
  { name: "Medellín", country: "Colombia" },
  { name: "Cartagena", country: "Colombia" },
  { name: "Lima", country: "Peru" },
  { name: "Santiago", country: "Chile" },
  { name: "Montevideo", country: "Uruguay" },
  { name: "Panama City", country: "Panama" },
  { name: "San José", country: "Costa Rica" },
  { name: "Quito", country: "Ecuador" },
  { name: "Havana", country: "Cuba" },
  { name: "Kingston", country: "Jamaica" },
  { name: "San Juan", country: "Puerto Rico" },
  { name: "Nassau", country: "Bahamas" },
  { name: "Moscow", country: "Russia" },
  { name: "St. Petersburg", country: "Russia" },
  { name: "Kyiv", country: "Ukraine" },
  { name: "Baku", country: "Azerbaijan" },
  { name: "Tbilisi", country: "Georgia" },
  { name: "Yerevan", country: "Armenia" },
  { name: "Almaty", country: "Kazakhstan" },
  { name: "Tashkent", country: "Uzbekistan" },
];

const LEISURE_DESTINATIONS = [
  { name: "Maldives", country: "Indian Ocean" },
  { name: "Santorini", country: "Greece" },
  { name: "Mykonos", country: "Greece" },
  { name: "Bodrum", country: "Turkey" },
  { name: "Amalfi Coast", country: "Italy" },
  { name: "Positano", country: "Italy" },
  { name: "Portofino", country: "Italy" },
  { name: "Lake Como", country: "Italy" },
  { name: "Capri", country: "Italy" },
  { name: "Tuscany", country: "Italy" },
  { name: "Cinque Terre", country: "Italy" },
  { name: "Forte dei Marmi", country: "Italy" },
  { name: "Costa Smeralda", country: "Italy" },
  { name: "Taormina", country: "Italy" },
  { name: "Ravello", country: "Italy" },
  { name: "Puglia", country: "Italy" },
  { name: "Sicily", country: "Italy" },
  { name: "Sardinia", country: "Italy" },
  { name: "Amalfi", country: "Italy" },
  { name: "Ibiza", country: "Spain" },
  { name: "Mallorca", country: "Spain" },
  { name: "Formentera", country: "Spain" },
  { name: "Tulum", country: "Mexico" },
  { name: "Riviera Maya", country: "Mexico" },
  { name: "Cancún", country: "Mexico" },
  { name: "Los Cabos", country: "Mexico" },
  { name: "Seychelles", country: "Indian Ocean" },
  { name: "Mauritius", country: "Indian Ocean" },
  { name: "Bali", country: "Indonesia" },
  { name: "Phuket", country: "Thailand" },
  { name: "Koh Samui", country: "Thailand" },
  { name: "Dubrovnik", country: "Croatia" },
  { name: "Hvar", country: "Croatia" },
  { name: "Split", country: "Croatia" },
  { name: "Kotor", country: "Montenegro" },
  { name: "Saint-Tropez", country: "France" },
  { name: "Côte d'Azur", country: "France" },
  { name: "Antibes", country: "France" },
  { name: "Cannes", country: "France" },
  { name: "Courchevel", country: "France" },
  { name: "Chamonix", country: "France" },
  { name: "St. Moritz", country: "Switzerland" },
  { name: "Verbier", country: "Switzerland" },
  { name: "Gstaad", country: "Switzerland" },
  { name: "Zermatt", country: "Switzerland" },
  { name: "Aspen", country: "United States", state: "Colorado" },
  { name: "The Hamptons", country: "United States", state: "New York" },
  { name: "Napa Valley", country: "United States", state: "California" },
  { name: "Vail", country: "United States", state: "Colorado" },
  { name: "Turks and Caicos", country: "Caribbean" },
  { name: "Barbados", country: "Caribbean" },
  { name: "St. Barts", country: "Caribbean" },
  { name: "Anguilla", country: "Caribbean" },
  { name: "Mustique", country: "Caribbean" },
  { name: "Bora Bora", country: "French Polynesia" },
  { name: "Fiji", country: "Pacific" },
  { name: "Rhodes", country: "Greece" },
  { name: "Paros", country: "Greece" },
  { name: "Corfu", country: "Greece" },
  { name: "Crete", country: "Greece" },
  { name: "Zanzibar", country: "Tanzania" },
  { name: "Azores", country: "Portugal" },
  { name: "Algarve", country: "Portugal" },
  { name: "Douro Valley", country: "Portugal" },
  { name: "Lapland", country: "Finland" },
  { name: "Norwegian Fjords", country: "Norway" },
  { name: "Patagonia", country: "Argentina" },
  { name: "Machu Picchu", country: "Peru" },
  { name: "Queenstown", country: "New Zealand" },
  { name: "Cape Winelands", country: "South Africa" },
  { name: "Masai Mara", country: "Kenya" },
  { name: "Serengeti", country: "Tanzania" },
  { name: "Okavango Delta", country: "Botswana" },
  { name: "Petra", country: "Jordan" },
  { name: "Wadi Rum", country: "Jordan" },
  { name: "Oman Desert", country: "Oman" },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log(`Connected to MongoDB: ${MONGO_URI}`);

  for (const city of WORLDWIDE_CITIES) {
    const isCapital = CAPITALS.has(city.name);
    const countryCode = COUNTRY_CODES[city.country] || '';

    await CityModel.findOneAndUpdate(
      { name: city.name, country: city.country },
      {
        $set: {
          ...city,
          isCapital,
          isDestination: false,
          countryCode,
        },
      },
      { upsert: true },
    );
  }
  console.log(`Seeded ${WORLDWIDE_CITIES.length} worldwide cities`);

  for (const dest of LEISURE_DESTINATIONS) {
    const countryCode = COUNTRY_CODES[dest.country] || '';

    await CityModel.findOneAndUpdate(
      { name: dest.name, country: dest.country },
      {
        $set: {
          ...dest,
          isCapital: false,
          isDestination: true,
          countryCode,
        },
      },
      { upsert: true },
    );
  }
  console.log(`Seeded ${LEISURE_DESTINATIONS.length} leisure destinations`);

  const total = await CityModel.countDocuments();
  console.log(`Total cities in database: ${total}`);

  const capitalCount = await CityModel.countDocuments({ isCapital: true });
  console.log(`Capital cities: ${capitalCount}`);

  await mongoose.disconnect();
  console.log('Done.');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
